site_name: PKT Documentation
site_url: https://docs.pkt.cash/
site_author: PKT
site_description: ""
repo_url: "https://github.com/pkt-cash/pkt-docs"

plugins:
  - search

theme:
  name: moonstone
  custom_dir: custom_theme
  fluid_layout: false


nav:
  - Home: index.md
  - PKT Network:
    - What is PKT Network: network/what-is-network.md
    - An Open Ecosystem: network/open-ecosystem.md
  - Staking:
    - Stake to earn: stake/stake-earn.md
    - How to stake: stake/how-to.md
    - Community Liquidity: stake/community-liquidity.md
    - How to stake LP: stake/stake-lp.md
    - How to stake LP tokens: stake/stake-lp-tokens.md
  - Migration airdrop: airdrop.md
  - Infrastructure:
    - Infrastructure: infra/infrastructure.md
    - VPN Exit: infra/vpn-exit.md
    - Setup a Cjdns Node: infra/cjdns-node.md
    - PKT VPN: infra/vpn.md
    - Setup a VPN Exit Node: infra/exit-node.md
    - Setup a Domain Node: infra/domain-node.md
    - Setup a Nameserver Node: infra/nameserver.md
    - Setup a Route Server Node: infra/route-server.md
    - Build a Website in PKT Network: infra/build-web.md
    - Accessing your cjdns website: infra/cjdns-web.md
  - Tockenomics:
    - Initial Distribution: tockenomics/initial-distribution.md
    - Migration Airdrop: tockenomics/airdrop.md
    - Token Supply: tockenomics/token.md
    - Proof-of-Stake Voting: tockenomics/voting.md
    - Development Team Allocation: tockenomics/dev-team.md
  - Affiliate: affiliate.md
  - How to buy PKT: buy-pkt.md
  - Wallets:
    - How to setup a PKT Wallet: wallet_setup/pkt-wallet-setup.md
    - Installing from Seed: wallet_setup/install-from-seed.md
    - Installing PKT Electrum (Mac/Windows): wallet_setup/install-pkt-electrum.md
    - Installing PKT.World Wallet (Mac/Windows): wallet_setup/pkt-world-wallet.md
    - Installing PKT Zulu Wallet (Mac): wallet_setup/pkt-zulu-wallet.md
    - Installing PKT CLI Wallet (Mac/Windows/Linux): wallet_setup/pkt-cli-wallet.md
  - Utility:
    - Introduction: utility.md
    - Content & Media: utility/content.md
    - BIA: utility/bia.md
    - Ecommerce: utility/ecommerce.md
    - Bandwidth Markets: utility/markets.md
    - Payments Transparency: utility/transparency.md
  - Governance:
    - Introduction: governance.md
    - Network Steward Charter: governance-nsc.md
  - Community:
    - Code of Conduct: community/code_of_conduct.md
    - Ethical Communication Guidelines: community/ethica-communication-guidelines.md
    - Examples to Avoid: community/avoid-examples.md
    - Better Examples: community/better-examples.md
  - Brand Assets: community/press-media-assets.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list


extra_css:
    - css/extra.css